apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd
spec:
  project: k8s-learning

  source:
    repoURL: https://github.com/zross11/k8s-learning.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true