# Default values for hell-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.21.6

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}